[package]

name = "iron-kaleidoscope"
version = "0.0.1"
authors = ["Jauhien Piatlicki <jauhien@gentoo.org>"]
build = "build.rs"

[dependencies]
docopt = "*"
docopt_macros = "*"
regex = "*"
regex_macros = "*"
rustc-serialize = "*"
