[package]

name = "iron-kaleidoscope"
version = "0.0.1"
authors = ["Jauhien Piatlicki <jauhien@gentoo.org>"]
build = "build.rs"

[dependencies.docopt_macros]
git = "git://github.com/docopt/docopt.rs"
