[package]

name = "iron_kaleidoscope"
version = "0.0.1"
authors = ["Jauhien Piatlicki <jauhien@gentoo.org>"]

[dependencies]
docopt = "0.6"
llvm-sys = "*"
llvm-ir = { version = "0.7.4", features = ["llvm-10"] }
regex = "1.4.3"
regex-macro = "0.1.1"
rustc-serialize = "0.3.24"

